/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package korrow;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kantarat
 */
public class GuiBorrowProfile extends javax.swing.JDialog {
    public static String tempUserName4;
    public static String lender ;
    public static String reCur;
    private static String cur;
    private static String itemId;

    public static String getItemId() {
        return itemId;
    }

    public static void setItemId(String itemId) {
        GuiBorrowProfile.itemId = itemId;
    }

    public static String getCur() {
        return cur;
    }

    public static void setCur(String cur) {
        GuiBorrowProfile.cur = cur;
    }

    public static String getReCur() {
        return reCur;
    }

    public static void setReCur(String reCur) {
        GuiBorrowProfile.reCur = reCur;
    }

    public GuiBorrowProfile() {
    }

    public String getLender() {
        
        return lender;
    }

    public void setLender(String lender) {
        this.lender = lender;
    }

    public static String getTempUserName4() {
        return tempUserName4;
    }

    public static void setTempUserName4(String tempUserName4) {
        GuiBorrowProfile.tempUserName4 = tempUserName4;
    }

    public void showProfile() {
        String pass;
        try {
            
            String sql = "select * from User where user_id='" + GuiBorrowProfile.tempUserName4 + "'";
            
            Connection con = Db1.getConnectionBuilder();
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = con.createStatement().executeQuery(sql);
//            ResultSet rs = statement.executeQuery();
            
            statement.executeQuery();            
            if (rs.next()) {
                String textId = rs.getString("user_id");
                jTextField1.setText(textId);
                String textName = rs.getString("user_name");
                jTextField2.setText(textName);
                String textPosition = rs.getString("user_position");
                jTextField3.setText(textPosition);
                String textEmail = rs.getString("user_email");
                jTextField4.setText(textEmail);
                String textTel = rs.getString("user_tel");
                jTextField5.setText(textTel);
                String textType = rs.getString("user_type");
                jTextField6.setText(textType);
                pass= rs.getString("user_password");
                int gdp = rs.getInt("gdp");
                String strGDP = gdp+" points";
                jTextField7.setText(strGDP);
                
                
            }
            statement.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Creates new form GuiBorrow
     */
    public GuiBorrowProfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_acc = new javax.swing.JButton();
        jButton2_noacc = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_acc.setText("อนุมัติ");
        jButton1_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_accActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jButton2_noacc.setText("ไม่อนุมัติ");
        jButton2_noacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_noaccActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_noacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel9.setText("Profile");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, -1));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, -1));

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, -1));

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, -1));

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 70, -1));

        jLabel10.setText("Id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel11.setText("name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel12.setText("GDP");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel13.setText("E-mail");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel14.setText("Tel");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel15.setText("Type");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel1.setText("Position");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jTextField7.setEditable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_accActionPerformed
        // TODO add your handling code here:
        try{
                
                Connection con = Db1.getConnectionBuilder();
                PreparedStatement ps = con.prepareStatement("UPDATE Transaction SET transaction_status=? WHERE transaction_id='" + getLender() + "'" );
                System.out.println("lender : "+getLender());
                //String hash=  TranGUI.statusDesc.get(check);
                //System.out.println(hash);
                ps.setInt(1,2);
               
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null," Update Success");
                
            }catch(Exception ex){
                Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_jButton1_accActionPerformed

    private void jButton2_noaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_noaccActionPerformed
        // TODO add your handling code here:+-
        long curRe = 0 ;
         try{
               
                Connection con = Db1.getConnectionBuilder();
                PreparedStatement ps = con.prepareStatement("UPDATE Transaction,Item SET Transaction.transaction_status=?, Item.item_current_amount=? "
                        + "WHERE Transaction.transaction_id='" + getLender() + "' and Item.item_id='"+getItemId()+"' " );
                String sql = "select item_current_amount from Item where Item_Id = '"+getItemId()+"'";
                PreparedStatement pre = con.prepareStatement(sql);
                ResultSet rs = con.createStatement().executeQuery(sql);
                if(rs.next()){
                     curRe = rs.getLong("item_current_amount");
                    System.out.println(curRe);
                }
                
                //String hash=  TranGUI.statusDesc.get(check);
                System.out.println("lender : "+getLender());
                long conlo = Long.parseLong(getReCur());
                //long conlo2 = Long.parseLong(getCur());//select datase ma yong mai kae
                long result = conlo+curRe;
                System.out.println("result : "+result);
                //System.out.println(hash);
                ps.setInt(1,-1);
                ps.setLong(2,result);
               
               
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null," Update Success");
                
            }catch(Exception ex){
                Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton2_noaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBorrowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBorrowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBorrowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBorrowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiBorrowProfile dialog = new GuiBorrowProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_acc;
    private javax.swing.JButton jButton2_noacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
