/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package korrow;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class GuiProfile extends javax.swing.JDialog {
    public static String tempUserName3;

    public static String getTempUserName3() {
        return tempUserName3;
    }

    public static void setTempUserName3(String tempUserName3) {
        GuiProfile.tempUserName3 = tempUserName3;
    }

   

    public GuiProfile() {
    }

    /**
     * Creates new form GuiProfile
     */
    public GuiProfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    String pass;
    public void showProfile() {
        try {
            User u = new User(); 
            String sql = "select * from User where user_id='" +u.getUserId() + "'";
            
            Connection con = Db1.getConnectionBuilder();
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = con.createStatement().executeQuery(sql);
//            ResultSet rs = statement.executeQuery();
            
            statement.executeQuery();            
            if (rs.next()) {
                String textId = rs.getString("user_id");
                field_id.setText(textId);
                String textName = rs.getString("user_name");
                field_name.setText(textName);
                String textPosition = rs.getString("user_position");
                field_position.setText(textPosition);
                String textEmail = rs.getString("user_email");
                field_email.setText(textEmail);
                String textTel = rs.getString("user_tel");
                field_tel.setText(textTel);
                String textType = rs.getString("user_type");
                field_type.setText(textType);
                pass= rs.getString("user_password");
                int gdp = rs.getInt("gdp");
                String strGDP = gdp+" points";
                field_GDP.setText(strGDP);
                
                
            }
            statement.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        field_id = new javax.swing.JTextField();
        field_name = new javax.swing.JTextField();
        field_position = new javax.swing.JTextField();
        field_email = new javax.swing.JTextField();
        field_tel = new javax.swing.JTextField();
        field_type = new javax.swing.JTextField();
        button_update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        field_GDP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 80, -1, -1));

        jLabel2.setText("name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 118, -1, -1));

        jLabel3.setText("position");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 162, -1, -1));

        jLabel4.setText("email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 200, -1, -1));

        jLabel5.setText("tel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 238, -1, -1));

        jLabel6.setText("type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 333, -1, -1));

        jLabel7.setText("Profile");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

        field_id.setEditable(false);
        getContentPane().add(field_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 77, 228, -1));
        getContentPane().add(field_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 115, 228, -1));
        getContentPane().add(field_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 159, 228, -1));
        getContentPane().add(field_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 197, 228, -1));
        getContentPane().add(field_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 235, 228, -1));

        field_type.setEditable(false);
        getContentPane().add(field_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 327, 228, -1));

        button_update.setText("update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });
        getContentPane().add(button_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 353, -1, -1));

        jLabel8.setText("GDP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 276, -1, -1));

        field_GDP.setEditable(false);
        getContentPane().add(field_GDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 273, 228, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        try {
            // TODO add your handling code here:
            User u =new User();
            u.setUserId(field_id.getText());
            u.setPassword(pass);
            u.setUserName(field_name.getText());
            u.setPosition(field_position.getText());
            ArrayList<String> arrListMail = new ArrayList<String>();
            String arrEmail[] = field_email.getText().split(",");
            for (String mail : arrEmail) {
                arrListMail.add(mail);
            }
            u.setEmail(arrListMail);
            String arrTel[] = field_tel.getText().split(",");
            ArrayList<String> arrListTel = new ArrayList<String>();
            for (String tel : arrTel) {
                arrListTel.add(tel);
            }
            u.setTel(arrListTel);
            u.setUserTypeId(field_type.getText());
            u.updateUser();
        } catch (SQLException ex) {
            Logger.getLogger(GuiProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiProfile dialog = new GuiProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_update;
    private javax.swing.JTextField field_GDP;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_id;
    private javax.swing.JTextField field_name;
    private javax.swing.JTextField field_position;
    private javax.swing.JTextField field_tel;
    private javax.swing.JTextField field_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
